name: sumobot
description: Sumobot app by ESIEESPACE

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository

  editions_repository:
    path: packages/editions_repository

  news_repository:
    path: packages/news_repository

  robots_repository:
    path: packages/robots_repository



  bloc: ^8.0.3
  flutter_bloc: ^8.0.1


  url_launcher: ^6.0.20
  html_unescape: ^2.0.0

  photo_view: ^0.13.0
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.2.0
  vibration: ^1.7.3
  image_picker: ^0.8.4+11
  equatable: ^2.0.3
  formz: ^0.4.1


  font_awesome_flutter: ^9.2.0

  onesignal_flutter: ^3.3.0
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3


  path_provider: ^2.0.9

  animated_size_and_fade: ^3.0.0

  intl: ^0.17.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sumobot.png
    - assets/fake_avatar.png
    - assets/kit-sumobot.jpg
    - assets/sumo_front.svg
    - assets/sumo_face_200.png
    - assets/sumo_face_500.png
    - assets/sumobot_blanc.png
    - assets/plan.png
    - assets/T6iVgiU5VAQME8gXMZEM.png
    - assets/ymTcRxq0ouxefl0dp1YJ.png
