name: sumobot
description: Sumobot app by ESIEESPACE

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository

  tuple: ^1.0.3

  bloc: ^6.0.0
  flutter_bloc: ^6.0.0

  qr_flutter: ^3.1.0
  barcode_scan: ^3.0.1
  vibration: ^1.5.0
  fluro: ^1.6.3
  http: ^0.12.2
  image_picker: ^0.6.7+7
  path_provider: ^1.6.14
  equatable: ^1.2.3

  firebase_core: ^0.5.0

  onesignal_flutter: ^2.0.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^6.0.0

  firebase_crashlytics: ^0.1.4+1

  cloud_firestore: ^0.14.0+2

  firebase_storage: ^4.0.0

  intl: ^0.16.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/sumobot.png
    - assets/kit-sumobot.jpg
    - assets/sumo_front.svg
    - assets/sumo_face_200.png
    - assets/sumo_face_500.png
    - assets/sumobot_blanc.png
