name: news_repository
description: Dart package which manages the news domain.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  html_unescape: ^1.0.2

  webfeed: ^0.6.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0