name: robots_repository
description: Dart package which manages robots.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  editions_repository:
    path: ../editions_repository

  authentication_repository:
    path: ../authentication_repository

  flutter:
    sdk: flutter
  equatable: ^2.0.3
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  meta: ^1.7.0
  cloud_firestore: ^3.1.10
  path_provider: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter