name: robots_repository
description: Dart package which manages robots.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  editions_repository:
    path: ../editions_repository

  authentication_repository:
    path: ../authentication_repository

  flutter:
    sdk: flutter
  equatable: ^1.2.5
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_storage: ^4.0.1
  meta: ^1.2.3
  google_sign_in: ^4.5.5
  apple_sign_in: ^0.1.0
  cloud_firestore: ^0.14.1+3
  path_provider: ^1.6.21


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0